# Basic ArgoCD cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: argo-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31923
    hostPort: 8080
- role: worker
- role: worker
- role: worker